### ISSUE TITLE
Medicine service cohesion and notification service efficiency

### ISSUE THREAD

**Issue by Sladamos** [pikol93/PG_SLEMA#24]
Medicine service sometimes contains return await and sometimes await. It should be normalized. Also, there are two calls of Future.wait with addNotification, which is ineffective way of adding notifications due to reading hard drive multiple times and saving to it. It should be improved by creating methods in service and repository which allow to add multiple notifications with one hard drive reading.

**Comment by pikol93** [comment]
Nie robimy issue na GH. Zamykam.

**Comment by pikol93** [comment]
Issue odnosi się do [SLEMA-93](https://pgslema.atlassian.net/browse/SLEMA-93)
